# Generated by Django 2.2 on 2020-04-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200421_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicein',
            name='material',
        ),
    ]
