# Generated by Django 2.2 on 2020-04-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200427_0939'),
        ('user', '0001_initial'),
        ('basic', '0004_auto_20200421_2254'),
        ('stock', '0005_auto_20200427_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOperate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to='attachment/%Y/%m/%d', verbose_name='附件')),
                ('check', models.BooleanField(choices=[(True, '已审核'), (False, '未审核')], default=False, verbose_name='是否审核')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('operate', models.IntegerField(choices=[(1, '入库'), (2, '出库')], default=1, verbose_name='操作')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.Device')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.Warehouse')),
            ],
            options={
                'verbose_name': '设备入库表',
                'verbose_name_plural': '设备入库表',
            },
        ),
        migrations.DeleteModel(
            name='DeviceIn',
        ),
    ]
