# Generated by Django 2.2 on 2020-04-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.RemoveField(
            model_name='device',
            name='warehouse',
        ),
    ]
