# Generated by Django 2.2 on 2020-04-28 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200427_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_brands', to='basic.Wordbook', verbose_name='品牌'),
        ),
    ]
