# Generated by Django 2.2 on 2020-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbook',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='wordbook',
            name='parent',
        ),
        migrations.AddField(
            model_name='wordbook',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='_wordbook_parents_+', to='basic.Wordbook', verbose_name='上一级'),
        ),
        migrations.DeleteModel(
            name='CategoryShip',
        ),
    ]
