# Generated by Django 2.2 on 2020-04-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20200421_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkbookShip',
            new_name='WordbookShip',
        ),
    ]
